
# Datasource
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://<PG_HOST>:5432/todosdb
spring.datasource.username=todos_user
spring.datasource.password=TuPasswordSegura123!
spring.jpa.hibernate.ddl-auto=none


# JPA
spring.jpa.show-sql=true
